### ISSUE TITLE
Code won't compile in Arduino IDE 2.3.2

### ISSUE THREAD

**Issue by smad333** [la3pna/trackuino-1#7]
Code won't compile in Arduino IDE with the following errors:

C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp: In function 'void afsk_setup()':
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp:136:3: error: 'radio' was not declared in this scope
   radio.setup();
   ^~~~~
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp:136:3: note: suggested alternative: 'Radio'
   radio.setup();
   ^~~~~
   Radio
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp: In function 'void afsk_start()':
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp:160:3: error: 'radio' was not declared in this scope
   radio.ptt_on();
   ^~~~~
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp:160:3: note: suggested alternative: 'Radio'
   radio.ptt_on();
   ^~~~~
   Radio
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp: In function 'bool afsk_flush()':
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp:176:9: error: 'radio' was not declared in this scope
         radio.ptt_off();    // Release PTT
         ^~~~~
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\afsk.cpp:176:9: note: suggested alternative: 'Radio'
         radio.ptt_off();    // Release PTT
         ^~~~~
         Radio
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\gps.cpp:111:13: warning: 'gps_valid' was declared 'extern' and later 'static' [-fpermissive]
 static bool gps_valid = false;
             ^~~~~~~~~
In file included from C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\gps.cpp:19:0:
C:\Users\adaml\Desktop\trackuino-tracker-master\trackuino\gps.h:39:13: note: previous declaration of 'gps_valid'
 extern bool gps_valid;
             ^~~~~~~~~

Using library Wire at version 1.0 in folder: C:\Users\adaml\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\libraries\Wire 
Using library Etherkit Si5351 at version 2.1.4 in folder: C:\Users\adaml\Documents\Arduino\libraries\Etherkit_Si5351 
Using library LiquidCrystal at version 1.0.7 in folder: C:\Users\adaml\AppData\Local\Arduino15\libraries\LiquidCrystal 
exit status 1

Compilation error: 'radio' was not declared in this scope

**Comment by smad333** [comment]
Got it compile by un-commenting //static RadioHx1 radio; in afsk.cpp. Why is it commented out by default?
